### ISSUE TITLE
pulled down your repo it does not build with the following error

### ISSUE THREAD

**Issue by franciscodominguez** [spharris/pvwatts-java#1]
I was looking at your pvwatts-java repo to see if guice allowed loading the same library simultaneously. 

i get this error when i build the repo: 

1) Could not find a suitable constructor in io.github.spharris.ssc.SscModule. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at io.github.spharris.ssc.SscModule.class(SscModule.java:37)
  while locating io.github.spharris.ssc.SscModule
  at io.github.spharris.ssc.SscModuleFactory.create(SscModuleFactory.java:1)

1 error
	at io.github.spharris.ssc.IntegrationTestSscModule.createModule(IntegrationTestSscModule.java:31)

**Comment by spharris** [comment]
I've updated the repo so that all of the tests pass (for me...). Try again.

**Comment by franciscodominguez** [comment]
what version of the jdk are you using?


[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile
(default-testCompile) on project pvwatts-java: Compilation failure:
Compilation failure:

[ERROR]
/Users/fdominguez/git/pvwatts-java/src/test/java/io/github/spharris/pvwatts/service/IntegrationTestPvWatts4Service.java:[46,57]
cannot find symbol

[ERROR] symbol:   method
registerModule(com.fasterxml.jackson.datatype.guava.GuavaModule)

[ERROR] location: class com.fasterxml.jackson.databind.ObjectMapper

[ERROR]
/Users/fdominguez/git/pvwatts-java/src/test/java/io/github/spharris/pvwatts/service/IntegrationTestPvWatts5Service.java:[47,57]
cannot find symbol

[ERROR] symbol:   method
registerModule(com.fasterxml.jackson.datatype.guava.GuavaModule)

[ERROR] location: class com.fasterxml.jackson.databind.ObjectMapper

[ERROR] -> [Help 1]


$ mvn --version

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5;
2015-11-10T08:41:47-08:00)

Maven home: /Users/fdominguez/tools/apache-maven-3.3.9

Java version: 1.8.0_202, vendor: Oracle Corporation

Java home:
/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre

Default locale: en_US, platform encoding: UTF-8

OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"
